[package]
name = "csqrl/codify-plugin"
version = "3.0.0"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"

[dependencies]
DumpParser = "csqrl/dump-parser@0.1.1"
Highlighter = "boatbomber/highlighter@0.7.0"
Hooks = "kampfkarren/roact-hooks@0.5.0"
Packager = "csqrl/packager@0.1.1"
Promise = "evaera/promise@4.0.0"
Roact = "roblox/roact@1.4.4"
Rodux = "roblox/rodux@4.0.0-rc.0"
RoduxHooks = "solarhorizon/rodux-hooks@0.3.0"
Sift = "csqrl/sift@0.0.5"
StudioPlugin = "csqrl/studio-plugin@1.1.0"
StudioTheme = "csqrl/studio-theme@1.0.2"
